org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=768m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
kotlin.daemon.jvmargs=-Xmx2048m
kotlin.code.style=official

pluginGroup = com.logtosql
pluginName = Log To SQL
pluginVersion = 1.0.0

platformVersion = 2024.2.5
platformType = IC
